in case of memcached failure will return same as if item is not cached
InterNations/ZendCacheMemcacheTaggingBackend pull request #3
Opened 2017-04-04 13:33 UTC by Gamesh

in case of failure memcached return false, this will return an empty array as if the tags where not cached at all

2017-04-04 14:10 UTC, lstrojny commented
Can you add an integration test for it?

2017-04-08 10:35 UTC, Gamesh commented
added integration test, had to refactor a bit \InterNations\Component\Caching\Tests\Zend\Integration\AbstractIntegrationTest to be able to stop start/stop servers from the test

2017-04-27 14:41 UTC, lstrojny requested changes

2017-04-27 14:41 UTC, lstrojny commented on tests/InterNations/Component/Caching/Zend/Integration/LibmemcachedIntegrationTest.php
> +        $this->assertEquals(Memcached::RES_SUCCESS, $this->backend->getMemcache()->getResultCode());
assertSame()

2017-04-27 14:41 UTC, lstrojny commented on tests/InterNations/Component/Caching/Zend/Integration/LibmemcachedIntegrationTest.php
> +        $this->assertEquals(static::MEMCACHED_CONNECTION_FAILURE, $this->backend->getMemcache()->getResultCode());
assertSame()

2017-04-27 14:41 UTC, lstrojny commented on tests/InterNations/Component/Caching/Zend/Integration/LibmemcachedIntegrationTest.php
> +        $this->assertEquals([], $resultAfterConnectionFailure);
assertSame()

2017-04-28 13:19 UTC, merged

2017-04-28 13:19 UTC, lstrojny commented
Yippieh!